### ISSUE TITLE
Where is output file???

### ISSUE THREAD

**Issue by ZhangSanMo** [nphdang/gSpan#1]
I have run this program sucessfully. But I can't find out my output file.

**Comment by nphdang** [comment]
To run the program, you use the Windows console and type the command: fsg_miner.exe -graphset ./data/mutag/mutag_graph.txt -graphlabel ./data/mutag/mutag_label.txt -minsup 0.35 -fsg mutag_fsg.txt
The result will be save into the file named "mutag_fsg.txt" in the current working folder.
I just update the readme file so that you can see how to run and save the result.
https://github.com/nphdang/gSpan/blob/master/parallel_gSpan/README.md

**Comment by ZhangSanMo** [comment]
Thanks a lot.
